### ISSUE TITLE
ProgressBar: Templated value difficult to see when value is a low percentage

### ISSUE THREAD

**Issue by greg-noe-cdw** [primefaces/primefaces#13773]
### Describe the bug

Progress Bar was updated in PF 15:

> `value` label is now rendered inside the `value` div to match other PrimeTek libraries.

This seems to have the effect of putting the text inside the positive part of the bar itself:

```
<p:progressBar
  value="80"
  labelTemplate="50 / 63 days"
  displayOnly="true" />
```

![Image](https://github.com/user-attachments/assets/c47defa6-ad87-4219-a0d3-c71e5173a069)

But when the value is very low, the templated text spills out, which is especially bad as the default saga-blue theme is white text and a white background:

```
<p:progressBar
  value="20"
  labelTemplate="13 / 63 days"
  displayOnly="true" />
```

![Image](https://github.com/user-attachments/assets/d6e2ff6e-e88c-4ac3-937e-c7b8de041c27)

Here's the templated text highlighted:

![Image](https://github.com/user-attachments/assets/70b16bb0-bf45-4df8-9b31-3cbe9e098146)

### Reproducer

Put this in a relatively small width div:
```
<p:progressBar
  value="1"
  labelTemplate="1 / 63 days"
  displayOnly="true" />
```

### Expected behavior

We're making the long due upgrade from aristo to saga-blue, here's what our production progress bar looks like:

![Image](https://github.com/user-attachments/assets/b382e938-73ec-44e8-a940-ddc26718e050)

### PrimeFaces edition

Community

### PrimeFaces version

15.0.3

### Theme

saga-blue

### JSF implementation

Mojarra

### JSF version

4.0

### Java version

21

**Comment by melloware** [comment]
Thanks for the report I just fixed something similar but I think based on your example I need to improve it further.

https://github.com/primefaces/primefaces/pull/13764

**Comment by melloware** [comment]
Much better

![Image](https://github.com/user-attachments/assets/8f90d423-2b8f-47dd-86e8-57c232de285c)

**Comment by melloware** [comment]
15.0.4 is out let me know how it looks!

**Comment by pizzi80** [comment]
I'm trying to migrate from PrimeFaces 13 to PrimeFaces 15.0.13 
and it seems not resolved 

To me is the html structure that should be different, actually I see:

```
<div class="ui-progressbar ui-widget ui-widget-content ui-progressbar-determinate">
  <div class="ui-progressbar-value ui-widget-header" style="display:block;width:3%">
     <div class="ui-progressbar-label" style="display:block">21 of 1.000</div>
  </div>
</div>
```

while it should be 

```
<div class="ui-progressbar ui-widget ui-widget-content ui-progressbar-determinate">
  <div class="ui-progressbar-value ui-widget-header" style="display:block;width:3%"></div>
  <div class="ui-progressbar-label" style="display:block">21 of 1.000</div>
</div>
```

As a rule of thumb JS shouldn't be used to style the page ...

**Comment by melloware** [comment]
@pizzi80 this was done to match PrimeVue, primeReact, PrimeNG  to keep in line with other PrimeLibs as close as we can for future possible CSS / Figma collaboration.

See PrimeVue:

<img width="2083" height="1250" alt="Image" src="https://github.com/user-attachments/assets/1bee84e5-aa87-478b-93a9-ca684673eeaf" />

**Comment by pizzi80** [comment]
ok,

I've fixed by setting "position: unset;" to the progress bar value div


the bug is present in the other projects as well...

**Comment by melloware** [comment]
good workaround!
