### ISSUE TITLE
Cannot enter space in datatable cell edit with selection

### ISSUE THREAD

**Issue by firsthour** [primefaces/primefaces#2000]
## 1) Environment
- PrimeFaces version: 6.0.13
- Does it work on the newest PrimeFaces version? no
- Application server + version: Wildfly 10.0.0.Final
- Affected browsers: Firefox 50.1, Chrome 55, IE 11

## 2) Expected behavior

Be able to enter spaces while cell editing in a table that supports selection.

## 3) Actual behavior

Can't enter spaces, seems to defocus the cell editing but not actually submit it.

## 4) Steps to reproduce

Click in cell editing cell, try to enter space.

## 5) Sample XHTML

	<html xmlns="http://www.w3.org/1999/xhtml"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:p="http://primefaces.org/ui">
		
		<h:head />
		
		<h:body>
			<h:form>
				<p:dataTable id="testTable" var="row" value="#{testController.letters}"
					selectionMode="multiple" selection="#{testController.selected}" rowKey="#{row.letter}"
					editable="true" editMode="cell">
					<p:column headerText="Letter" sortBy="#{row.letter}">
						<h:outputText value="#{row.letter}" />
					</p:column>
					<p:column headerText="Text">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{row.text}" />
							</f:facet>
							<f:facet name="input">
								<p:inputText value="#{row.text}" style="width:96%" />
							</f:facet>
						</p:cellEditor>
					</p:column>
				</p:dataTable>
			</h:form>
		</h:body>
	</html>

## 6) Sample bean

	import java.io.Serializable;
	import java.util.Arrays;
	import java.util.List;
	
	import javax.faces.view.ViewScoped;
	import javax.inject.Named;
	
	@ViewScoped
	@Named
	public class TestController implements Serializable {
		private static final long serialVersionUID = 1L;
		
		public class Letter {
			String letter;
			String text;
			Letter(String letter, String text) {
				this.letter = letter;
				this.text = text;
			}
			public String getLetter() {
				return letter;
			}
			public String getText() {
				return text;
			}
			public void setText(String text) {
				this.text = text;
			}
		}
		
		private List<Letter> letters = Arrays.asList(new Letter("A", ""), new Letter("B", ""), new Letter("C", ""));
		private List<Letter> selected;
		
		public List<Letter> getLetters() {
			return letters;
		}
		
		public List<Letter> getSelected() {
			return selected;
		}
		
		public void setSelected(List<Letter> selected) {
			this.selected = selected;
		}
	}

**Comment by firsthour** [comment]
Any word on this? We've had to replace our existing in-cell editing with a dialog popup, but would really prefer the original method.

**Comment by the-killer-bee** [comment]
Hi,
I use PrimeFaces version: 6.0.13, and I get the same issue "I Can't enter spaces".
Using p:inplace resolve the issue, but it's not confortable when using roweditor.

Anyone could help us please ?

Thanks !

**Comment by mertsincan** [comment]
Fixed for 6.0.14 and 6.1.
https://github.com/primefaces/primefaces/issues/2015

**Comment by the-killer-bee** [comment]
Thanks a lot @mertsincan ,
Do you know when primefaces 6.0.14 or 6.1 will be available as we have presentation next week and this issue is really awkward.

Thanks a lot

**Comment by mertsincan** [comment]
Today :)

**Comment by firsthour** [comment]
This is awesome, thank you!

**Comment by harshal-kalavadiya** [comment]
Hi mertsincan,
I am still facing the same problem.
Please find my code below:

```
<p:tab id="sheetTabId" style="padding:0px 0px 0px 0px !important">									
<f:facet name="title">
	<h:panelGroup layout="block">
	<p:inputText id="tabNameId" value="#{tab.sheetName}" 
			style="width:100px;height: 10px;padding: 2px 2px 2px 2px !important"
			rendered="#{tab.flagButton}" maxlength="15" 
			valueChangeListener="#{projectInnovatorCharacterization.changeListener}">
		<f:attribute name="myattribute" value="Sheet Name" />
	</p:inputText>
	<p:watermark for="tabNameId" value="Sheet Name" id="watermark" />								
	<h:outputText value="#{tab.sheetName}" style="width:100px;"
			rendered="#{not tab.flagButton}" />
     </h:panelGroup>
</f:facet>
```

Here I am usung p:inputText inside f:facet and I am not able to enter space.
Primeface version : 6.1
Primfaces Extension Version : 6.0.0
Application Server : jboss-eap-7.0 / wildfly-10.1.0.Final
Can you please help me for this?
