### ISSUE TITLE
Spurious valueChange events in a Calendar with a datetime pattern

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces/primefaces#2811]
## 1) Environment
- PrimeFaces version: 6.1, 6.2-SNAPSHOT (c20c99950d01595e36c939259a7d1022644ceb14)
- The issue is present in both tested versions.
- The issue **is not** present in 5.2.12.
- Application server + version: Wildfly 10.1
- Affected browsers: Firefox 56, Chrome 61.

## 2) Expected behavior

The valueChange event should be triggered when the value actually changed and only once.

## 3) Actual behavior

An unneccesary/duplicate valueChange event is triggered on each calendar input blur. But only if the pattern includes both date and time.

## 4) Steps to reproduce

Have a p:calendar with a datetime pattern.
Input a value into the calendar input field and then lose focus by clicking somewhere else. See two valueChanges happening.
Leave the value in the field. Now just click inside the field and outside repeatedly. See valueChange happening on each blur even though the value is not changed at all.

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view locale="en">
	<h:head>
	</h:head>

	<h:body>
		<h:form>
			<h2>Bug: spurious valueChange events on blur</h2>
			<p>Datetime: 1. paste &quot;<span>01.01.2017 12:12</span>&quot; into the following text field and then lose focus by clicking somewhere else. See two valueChanges happening.</p>
			<p>2. Leave the value in the field. Now just click inside the field and outside repeatedly. See valueChange happening on each blur even though the value is not changed at all.</p>
			<p:outputLabel for="dt" value="datetime" />
			<p:calendar id="dt" pattern="dd.MM.yyyy HH:mm" widgetVar="dtVar">
				<p:ajax onstart="vc('dtVar');" />
			</p:calendar>

			<h2>No bug: valueChange event is triggered only when the value actually changed</h2>
			<p>Date: paste &quot;<span>01.01.2017</span>&quot; into the following text field and then lose focus by clicking somewhere else.</p>
			<p:outputLabel for="d" value="date" />
			<p:calendar id="d" pattern="dd.MM.yyyy" widgetVar="dVar">
				<p:ajax onstart="vc('dVar');" />
			</p:calendar>

			<p>Time: paste &quot;<span>12:12</span>&quot; into the following text field and then lose focus by clicking somewhere else.</p>
			<p:outputLabel for="t" value="time" />
			<p:calendar id="t" pattern="HH:mm" widgetVar="tVar">
				<p:ajax onstart="vc('tVar');" />
			</p:calendar>

			<h2>Each valueChange event will add a paragraph below...</h2>
			<script>
				function vc(wVar) {
					$('<p>valueChange: ' + PF(wVar).getDate() + '</p>').appendTo('body');
				}
			</script>
		</h:form>
	</h:body>
</f:view>
</html>
```

## 6) Sample bean

Unnecessary.

**Comment by tandraschko** [comment]
PR is welcome!

**Comment by jxmai** [comment]
The regression is from https://github.com/primefaces/primefaces/commit/c315e32b7b11d24d1fb2506d81c02152d4d66516 causing by upgrading timepicker during 6.0 RC3

Ticket: https://github.com/primefaces/primefaces/issues/1371

**Comment by jxmai** [comment]
And this line is extremely suspicious. https://github.com/primefaces/primefaces/commit/c315e32b7b11d24d1fb2506d81c02152d4d66516#diff-fb7f75dc88d243f1129be700515ce555L11645 

![image](https://user-images.githubusercontent.com/10467831/31529173-43e1140e-af9d-11e7-9cf1-4e81fb38634c.png)

It looks like there was a custom fix before but forgot to put back in during upgrade. 

Please examine if any more code like this since hacking the library directly is usually not a good idea.. 😅 .

**Comment by jxmai** [comment]
I was right. Please look at: https://code.google.com/archive/p/primefaces/issues/5702

![image](https://user-images.githubusercontent.com/10467831/31529278-d64067dc-af9d-11e7-982e-ee57fd722bea.png)

**Comment by melloware** [comment]
Nice detective work!

**Comment by melloware** [comment]
Should we put this patched line back the way it was?

**Comment by jxmai** [comment]
Not sure, I think it's better to let PF team to evaluate. However, I do think `1.6.3` is the last time-picker upgrade since that project has been no activity for a year  (https://github.com/trentrichardson/jQuery-Timepicker-Addon), so it might be safe to change their library this time.

![image](https://user-images.githubusercontent.com/10467831/31620586-3c3b2d80-b25d-11e7-9f65-88df30ba7c86.png)

**Comment by melloware** [comment]
I submitted this PR as after reviewing this was definitely fixed in the old timepicker from that Google Code issue.

**Comment by jxmai** [comment]
It should be safe to alter the time picker library this time :+1: .

**Comment by melloware** [comment]
Attached is runnable sample. 
[pf-2811.zip](https://github.com/primefaces/primefaces/files/2534903/pf-2811.zip)

**Comment by VsevolodGolovanov** [comment]
6.2.30: still happens, but only for timeOnly cases. Eh, good enough for me.
