### ISSUE TITLE
Component value removed if invalid

### ISSUE THREAD

**Issue by koflerdavidgrawe** [primefaces/primefaces#2821]
## 1) Environment
- PrimeFaces version: 6.1
- Does it work on the newest released PrimeFaces version? Version? No
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) Not tested, but assumed to not have changed
- Application server + version: Tomcat 8.0
- Affected browsers: Chrome (assumed all)

Prerequisite:
Instead of using JSF Phase 3 for Validation, we use our own validation framework. We set affected components invalid in Phase 5. (javax.faces.component.UIInput.setValid(boolean valid))

## 2) Expected behavior
Value is not removed. Entered value is rendered.

## 3) Actual behavior
Calendar: Entered Value is rendered.
InputText: Entered Value is removed. Empty String is rendered.

## 4) Steps to reproduce
Create any InputText and Calendar components.
Enter any value.
Call javax.faces.component.UIInput.setValid(false) on both in Phase 5.

## 5) Sample XHTML
Any Primefaces Calendar and InputText Component

## 6) Sample bean
Any Bean

## 7) Explanation:
During Phase 6:
Stacktrace InputText:
InputTextRenderer.encodeEnd(...)
InputTextRenderer.encodeMarkup(...)
ComponentUtils.getValueToRender(...)

if (config.isInterpretEmptyStringAsNull() && submittedValue == null && !input.isLocalValueSet() && context.isValidationFailed() && !input.isValid()) {
  return null;
}

Here, if the component is not valid, null is returned.
Calendar follows a very much alike procedure to get the value to render but does not have the given if statement.

## 8) Solution:
All input components should behave the same way. This should be either one predefined option (Input value stays in the field) or customizable (in case you dont want existing applications to behave differently).

**Comment by tandraschko** [comment]
Likely we won't change this behavior soon. It works fine since "years".

If you would like to change something here, we first have to create a bundle of unittests, to validate the current behavior.
If you can provide this unittests, we can go a step further, provide a unittest for your special case, fix it and discuss if the broken unittests are correct to be broken afterwards.

**Comment by koflerdavidgrawe** [comment]
This issue has a rather high priority to us and I think that a lot of people would agree. While deleting Username and Password on a login form is quite common, deleting entered values on any other input form has a deteriorating effect on usability.

The inverse request, reseting the value of a Calendar can be achieved rather easily using the "resetinput" component. For the given issue there is no proper workaround (e.g. exchanging the renderer is error prone on changes to the original)

Referring to your request for unit tests: I am not sure what kind of unit tests you expect. The method would after the change return the "old" value instead of returning null, which seems rather trivial. Furthermore the change should be easy to implement, even if you go the safer way of making it configurable.

**Comment by tandraschko** [comment]
I'm really not sure but how behaves the JSF impls here? I think they all clear the value, also see: https://issues.apache.org/jira/browse/MYFACES-3525

**Comment by koflerdavidgrawe** [comment]
As the comment history suggests, the spec is not exactly clear on the matter. The closing of java.net sadly makes the spec issue impossible to track.

PF having provided a way to reset input values on validation errors seems to have gone the way of doing it only on demand, which is the obviously more sensible option in this case.

The patch provided - as well as the workaround in the related issue (https://github.com/javaee/javaserverfaces-spec/issues/671) - reset the submitted value after invalidating the component, which seems to be an awkward way to bypass the if statement mentioned above, therefore i disagree with this workaround.

Considering clearing the input value might still be a valid assumption, the possibility of the spec being changed to support that, as well as not wanting to change existing applications, I suggest introducing a configurable parameter (like "reset input on validation error") which is enabled by default. New developments can bypass the behaviour. Still different input components would need to be adjusted to have consitent behaviour.

**Comment by koflerdavidgrawe** [comment]
Related: https://stackoverflow.com/questions/3933786/jsf-2-bean-validation-validation-failed-empty-values-are-replaced-with-las

**Comment by tandraschko** [comment]
Feel free to provide a PR - BUT - it will only work for primefaces components and not e.g. for h:inputText.
I think the parameter should be called "primefaces.DISPLAY_NULL_ON_VALIDATION_ERROR" as it doesn't reset anything, it just displays null.

**Comment by koflerdavidgrawe** [comment]
Thanks for the input. We currently lack the resources to do this, so we would appreciate if somebody would stand up to the task. Support could definitely be provided. We might find time ourselves for the task in the future.

**Comment by koflerdavidgrawe** [comment]
We have implemented a fix, which is seems to work. I will leave the code here for reference (inspired by https://github.com/javaee/javaserverfaces-spec/issues/671#issuecomment-299379611)

```java
private <T> void addErrorMessage(final UIInput inputComponent, final Collection<ConstraintViolation<T>> componentViolations) {
// the if statement which is affected by the setValid(false) call below is skipped
// (org.primefaces.util.ComponentUtils.getValueToRender(FacesContext context, UIComponent component, Object value))
// this method substitutes the call in e.g. org.primefaces.component.inputtext.InputTextRenderer.encodeMarkup(FacesContext context, InputText inputText)
// the assumption is taken that the value for this component is retrieved only by this method and until the actual call no relevant values would change
// this assumption is more likely to hold true since this call is done in Phase 5 instead of Phase 6, where little changes should be made
// Note: Calendar actually is rendered correctly
if (!(inputComponent instanceof Calendar)) {
  inputComponent.setSubmittedValue(ComponentUtils.getValueToRender(FacesContext.getCurrentInstance(), inputComponent));
}
inputComponent.setValid(false);
```

**Comment by tandraschko** [comment]
JFYI: the default behavior of JSF 2.3 is that value is always removed - completely ignoring isInterpretEmptyStringAsNull (https://github.com/javaee/javaserverfaces-spec/issues/671).
So this will likely be not fixed.

**Comment by elfwine** [comment]
@koflerdavidgrawe, I have the same dilemma, may I know which part of the code did you add those fix?
Btw, I am using Omnifaces' Messages utility to throw those error messages.

**Comment by koflerdavidgrawe** [comment]
@elfwine Im not quite sure what you mean? I did post our code changes in an earlier comment: https://github.com/primefaces/primefaces/issues/2821#issuecomment-337502096

**Comment by tandraschko** [comment]
I just tested PF with both Mojarra 2.3 and MyFaces 2.3 and the behavior is exactly the same when using a simple example (inputText with attached f:validateLength - also with avax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL true/false. 

I would be great if you could give 2.3 a try with your advanced example and check if p:inputText behaves different as h:inputText.

**Comment by elfwine** [comment]
@koflerdavidgrawe, nevermind about it, I figured it out already. Thanks anyway.

@tandraschko, I tested it with 2.3, yes you're right, both p:inputText and h:inputText have the same behavior. I understand JSF specs regarding about it, however with complex condition such as several inputs validations depends on some inputs, I feel like it's kinda frustrating to input data again if there's some validation errors.
Note: I only set UIInput.setValid(false) in ManagedBean side just to highlight (error style) the invalid components. If I don't use setValid(false), error message is display, the input data are untouched but no error highlights.

**Comment by tandraschko** [comment]
I think the best way would be to create a spec issue, to make it configurable for the upcoming version.

**Comment by tandraschko** [comment]
I will close it for now as we aligned with the specs.
The behavior is maybe not 100% nice but if we change it, it should also be in the next JSF version.
So please create a issue there first and start a dicussion.

**Comment by ghost** [comment]
I stumbled upon the exact same issue today. After doing some research, I have found an easy workaround. Workaround tested against Primefaces 6.2, JSF 2.3.3 on EAP 7.1

```
UIInput codeInputField = ....;

codeInputField.setValid(false);

codeInputField.setSubmittedValue(codeInputField.getValue());
```

After setting the valid field to false, we need to force the original value into the submitted value.
