### ISSUE TITLE
Datepicker: js error uncaught Extra/unparsed characters found in date (selectionMode="range")

### ISSUE THREAD

**Issue by majulvez** [primefaces/primefaces#4496]
## 1) Environment
- PrimeFaces version: 6.2.15 and 7.0-SNAPSHOT
- Does it work on the newest released PrimeFaces version? No. Version? 6.2.15
- Does it work on the newest sources in GitHub? No
- Application server + version: Apache Tomcat 7.0.62
- Affected browsers: Chrome/Firefox

## 2) Expected behavior
Datepicker shows the range of dates selected in the calendar (today and tomorrow)

## 3) Actual behavior
Datepicker shows a javascript error 'Uncaught Extra/unparsed characters found in date: -5/02/19'

## 4) Steps to reproduce
Just load the .xhtml page and look in the web browser console

## 5) Sample XHTML
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
>

<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <title>PrimeFaces Showcase</title>

    <script type="text/javascript">
        PrimeFaces.locales['es'] = {
            closeText: 'Cerrar',
            prevText: 'Anterior',
            nextText: 'Siguiente',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],
            dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
            weekHeader: 'Semana',
            firstDayOfWeek: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: '',
            timeOnlyTitle: 'Sólo hora',
            timeText: 'Tiempo',
            hourText: 'Hora',
            minuteText: 'Minuto',
            secondText: 'Segundo',
            currentText: 'Fecha actual',
            ampm: false,
            month: 'Mes',
            week: 'Semana',
            day: 'Día',
            allDayText: 'Todo el día'
        };
    </script>

</h:head>
<h:body>
    <h1>Datepicker</h1>

    <h:form id="form">
        <p:datePicker value="#{calendarView.dates}" locale="es" selectionMode="range" numberOfMonths="2" />
    </h:form>

</h:body>
</html>
```

## 6) Sample bean
```
package com.primefaces.test;

import javax.faces.bean.ManagedBean;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

@ManagedBean(name = "calendarView")
public class CalendarView implements Serializable {

    private String test = "test";

    private List<Date> dates;

    public CalendarView() {
        Date today = Calendar.getInstance().getTime();
        long oneDay = 24 * 60 * 60 * 1000;
        Date tomorrow = new Date(today.getTime() + (1 * oneDay));

        dates = new ArrayList<>();
        dates.add(today);
        dates.add(tomorrow);

    }

    public List<Date> getDates() {
        return dates;
    }

    public void setDates(List<Date> dates) {
        this.dates = dates;
    }

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }
}
```

**Comment by melloware** [comment]
Attached is a runnable sample: 
[pf-datepicker.zip](https://github.com/primefaces/primefaces/files/2827898/pf-datepicker.zip)

Just run "mvn clean jetty:run-exploded" and navigate to http://localhost:8080/primefaces-test/test.xhtml

It appears this is fixed in the upcoming 7.0 and most likely in 6.2.16.

**Comment by tandraschko** [comment]
@mertsincan can you verify?

**Comment by majulvez** [comment]
Thanks @melloware , but if you use inline="true" property in your example, you'll see that the range given is not showed

**Comment by melloware** [comment]
@majulvez Then you should have had inline in your example code above. I literally copied and pasted what you had.  I just ran it with inline="true" and I still get no JS errors and my screen looks like this...

![image](https://user-images.githubusercontent.com/4399574/52218641-1295e000-2869-11e9-8cd0-2315dc25552c.png)

**Comment by majulvez** [comment]
I meant with your example no js errors is showed (not like in 6.2.15) but I still don't see that range selected. I've tested with chrome and firefox (last version).

I told you about inline="true" because is easier to see the behaviour.

This is what I see

https://imgur.com/a/Scyaph4

**Comment by melloware** [comment]
I selected that range by hand.  So I guess the real bug here is that its not preselecting the dates from the backing beans values.  That is the bug.

**Comment by majulvez** [comment]
Yes. That is what I was testing when I see the js error. It's wrote down in the expected behaviour in the issue.

Thanks

**Comment by melloware** [comment]
Right I was focused on that the JS Error was your problem.  Not the fact its not preselecting the dates.  @mertsincan this is definitely an issue you can test with my test case above.

**Comment by mertsincan** [comment]
Hi @majulvez and @melloware,

Could you please check my fix? Thanks a lot!

**Comment by majulvez** [comment]
Hi @mertsincan ,

I still don't see the dates preselected when the calendar is showed

Thanks

**Comment by mertsincan** [comment]
Hi, 
>Datepicker shows a javascript error 'Uncaught Extra/unparsed characters found in date: -5/02/19'

Is this issue resolved?

**Comment by mertsincan** [comment]
> I still don't see the dates preselected when the calendar is showed

Please see; https://github.com/primefaces/primefaces/issues/4514

Could you please check #4514 fix? Thanks,

**Comment by majulvez** [comment]
Yes. It works fine now. 

Thanks
