### ISSUE TITLE
TreeTable/Datatable: Dynamic Columns Issue

### ISSUE THREAD

**Issue by goraSi** [primefaces/primefaces#5117]
## 1) Environment
- PrimeFaces version: 7.0
- Does it work on the newest released PrimeFaces version? Version? NO
- Does it work on the newest sources in GitHub? (Build by source -> https://github.com/primefaces/primefaces/wiki/Building-From-Source) NO
- Application server + version: ALL
- Affected browsers: ALL

## 3) Actual behavior
```
org.primefaces.component.api.DynamicColumn cannot be cast to org.primefaces.component.column.Column: java.lang.ClassCastException: org.primefaces.component.api.DynamicColumn cannot be cast to org.primefaces.component.column.Column
	at org.primefaces.component.treetable.TreeTable.updateColumnsVisibility(TreeTable.java:655)
	at org.primefaces.component.treetable.TreeTableRenderer.preRender(TreeTableRenderer.java:226)
	at org.primefaces.component.treetable.TreeTableRenderer.encodeEnd(TreeTableRenderer.java:161)
```

## 4) Steps to reproduce
Press "Refresh" button

## 5) Sample XHTML
```
<h:form id="form">
	<p:commandButton value="Refresh" update="@form" />
	<p:commandButton id="toggler" type="button" value="Columns" style="float:right" icon="ui-icon-calculator" />
	<p:columnToggler datasource="idDataTable" trigger="toggler" />

	<p:treeTable id="idDataTable" var="cars" value="#{tableBean.carsTree}">
		<p:column value="Column">
			<h:outputText value="Column" />
		</p:column>
		<p:columns value="#{tableBean.columns}" var="column" columnIndexVar="columnIndx" visible="true">
			<f:facet name="header">
				#{column.header}
			</f:facet>
			<h:outputText value="#{cars[column.property]}" />
		</p:columns>
	</p:treeTable>
</h:form>
```

## 6) Sample bean
```
public class TableBean implements Serializable {
    private List<ColumnModel> columns = new ArrayList<ColumnModel>();
    private DefaultTreeNode carsTree = new DefaultTreeNode();

	public TableBean() {
        populateColumns();
        
        Car car = new Car();
        car.setManufacturer("Audi");
        car.setModel("A4");
        car.setYear(2015);
        new DefaultTreeNode(car, carsTree);
    }

    public void populateColumns() {
        String[] columnKeys = new String[]{"model","year","color"};
        for(String columnKey : columnKeys) {
            columns.add(new ColumnModel(columnKey.toUpperCase(), columnKey));
        }
    }
    //getters and setters

    public List<ColumnModel> getColumns() {
		return columns;
	}

	public void setColumns(List<ColumnModel> columns) {
		this.columns = columns;
	}

    public DefaultTreeNode getCarsTree() {
		return carsTree;
	}

	public void setCarsTree(DefaultTreeNode carsTree) {
		this.carsTree = carsTree;
	}

	static public class ColumnModel {
        private String header;
        private String property;

        public ColumnModel(String header, String property) {
            this.header = header;
            this.property = property;
        }
        public String getHeader() {
            return header;
        }
        public String getProperty() {
            return property;
        }
    }
}
```

**Comment by tandraschko** [comment]
Bean missing -> invalid

**Comment by melloware** [comment]
The error says TreeTable but the example above is using DataTable not TreeTable?  Or am I missing something?

**Comment by goraSi** [comment]
> The error says TreeTable but the example above is using DataTable not TreeTable? Or am I missing something?

The error happens in both cases. The problem lies in "columnToggler" which triggers method.

**Comment by melloware** [comment]
OK so I just tested ColumnToggler with datatable with your exact scenario above and it works fine?

So can you please provide and example that actually works?  According to the PrimeFaces Showcase they don't have an example using TreeTable + ColumnToggler?

**Comment by melloware** [comment]
I definitely think it is a bug I would just like a working example code to test with.

**Comment by goraSi** [comment]
I have updated XHTML and bean.

**Comment by melloware** [comment]
Thank you!  Attached is test case proving the issue: 
[pf-5117.zip](https://github.com/primefaces/primefaces/files/3591001/pf-5117.zip)

**Comment by melloware** [comment]
OK I definitely don't understand how DynamicColumns work because I was able to get the error to stop by casting correctly but how to change the visibility of the Dynamic Columns I cannot figure out.

I changed the code to this...
```java
                if (column != null) {
                    Boolean visible = Boolean.valueOf(togglableColumn.substring(sepIndex + 1));
                    if (column instanceof Column) {
                        ((Column) column).setVisible(visible);
                    }
                    else {
                        ((DynamicColumn) column).setVisible(visible);
                    }
                }
```

But it only works if you change the last column to invisible but then it makes ALL your Dynamic columns invisible.  Need help from others on this one.

**Comment by goraSi** [comment]
any updates on this

**Comment by melloware** [comment]
No update other than I can make the NPE go away but I can't get it to respect the checkboxes for the Dynamic Columns.  I am just an open source community helper you may have to engage PrimeFaces Support and ask for a quote for how much to fix this issue if you don't have PRO support: https://www.primefaces.org/support/  You can click "get a quote" button.

**Comment by fanste** [comment]
@melloware You have to update the model behind the dynamic columns. That is mainly the same mechanism as it is used for any iterating component with their `rowIndex`.

```
else {
    DynamicColumn dynamicColumn = (DynamicColumn) column;
    column.applyModel();
    column.setVisible(visible);
}
```

**Comment by melloware** [comment]
@fanste  I tried that and it still is not working correctly.  If you check the Price column which is the last column it hides ALL the columns. However if you hid the Brand column it immediately comes back after you press the Refresh button.

**Comment by melloware** [comment]
I think this bug is actually similar to this issue: https://github.com/primefaces/primefaces/issues/4582

**Comment by fanste** [comment]
I had a look at it and the problem is that the `StateHelper` used by `DynamicColumn > Columns#isVisisble` is component-specific and not row-specific. That means: `applyModel()` replaces the data but not the state helper. Therefore the last column will always overwrite the visibility value of the previous columns.

But I have no idea how this should be fixed.

**Comment by melloware** [comment]
I 100% agree with your assessment.  You came to the exact conclusion I did and I also don't know how to proceed to fix this.

**Comment by goraSi** [comment]
Any updates on this? I'm rolling out new release of my app soon and would like to include Primefaces 7.x because of other great features but this is currently showstopper for me.

**Comment by tandraschko** [comment]
if it's a showstopper, i really suggest to dig into it and provide a PR. Otherwise you can sponsor it via PrimeFaces PRO.

**Comment by tandraschko** [comment]
i refactored it now and fixed the exception but it still doesnt work and all columns are hidden

**Comment by tandraschko** [comment]
the impl in DataTable is completely different. It doesnt use setVisible and handle the state in a own Map. I assume the DataTable impl is also broken when you update the datatable+proces=buttonOnly+partialSubmit.

The impl in TreeTable would be better if working but it also misses MVS for the toggler.

**Comment by tandraschko** [comment]
yeah, both DT and TT are broken actually....

**Comment by tandraschko** [comment]
puh, the Table and Columns hell...
@Rapster i actually dont like to refactor further but couldnt we in theory support multiple p:columns? Currently the DynamicColumnsListener makes it a 1:1 dependency but i dont understand the DynamicColumnsListener actually, we always collect it/iterate over the children (UITable#forEachColumn)

**Comment by Rapster** [comment]
Yes I don't see any reason why we couldn't support multiple `p:columns`, should be quite easy with `UITable#forEachColumn`. Commit 0ec44a5478ebf025d671b867c9af54177eef9502 doesn't say much, but originally it looks like specific to TreeTable. Would it be just because of this?

```java
@Override
    public Object saveState(FacesContext context) {
        if(this.dynamicColumns != null) {
            dynamicColumns.setRowIndex(-1);
        }

        return super.saveState(context);
    }  
```

**Comment by tandraschko** [comment]
no idea TBH

**Comment by tandraschko** [comment]
fixed it now

in general i think its related to "preserveRowState" of p:columns. I now switched TreeTable to handle it the same like in DataTable.

@Rapster would be great if you can review. I will propably align "resizable columns", too to only handle one map and not map+string.


@melloware there is a small bug somewhere in the rendering part that always "almost 2 columns" are rendered if you deselect all columns but 1. The "visible columns state" is correct, i think there is something wrong in the rendering and JS part. Do you have time to check this?

**Comment by melloware** [comment]
I can look at that part see if I can find the issue in the JS.

**Comment by tandraschko** [comment]
there are 2 issues, for both Tree and DataTable.
If you deselect all but 1 column via JS, there are still "almost 2" columns rendered.
If you update it via ajax, there is only 1 column toggled and also "almost 2" columns rendered.

I will add my example here

**Comment by tandraschko** [comment]
[pf-5117.zip](https://github.com/primefaces/primefaces/files/5689923/pf-5117.zip)

**Comment by melloware** [comment]
For some reason I can't unzip your reproducer its giving me a corrupted zip file?

**Comment by tandraschko** [comment]
my local one isnt corrupted, uploaded it again.

[pf-5117.zip](https://github.com/primefaces/primefaces/files/5689965/pf-5117.zip)

**Comment by tandraschko** [comment]
yep, should be fine

**Comment by melloware** [comment]
I am using Windows 10 and whenever I try and unzip I get this: 
![image](https://user-images.githubusercontent.com/4399574/102104636-6b871580-3dfc-11eb-8504-606162e4f8e6.png)

**Comment by tandraschko** [comment]
[pf-5117 (2).zip](https://github.com/primefaces/primefaces/files/5690010/pf-5117.2.zip)

now compressed with windows, before i used 7z

**Comment by melloware** [comment]
Got it now. Debugging...

**Comment by melloware** [comment]
OK I debugged.  here is what I see.

1. Yes all 4 columns are marked `false` in the AJAX call in `columnTogglerState`

2. All 4 column headers are marked `ui-helper-hidden` correctly.
![image](https://user-images.githubusercontent.com/4399574/102114163-e3a70880-3e07-11eb-91c7-2567ecb72160.png)

3. However 3 of the 4 BODY columns are marked `ui-helper-hidden` and when I debug the `TreeTableRenderer.encodeNode` I can see the first call to columnVisible=true and the next 3 are false.
![image](https://user-images.githubusercontent.com/4399574/102114368-19e48800-3e08-11eb-99dd-ac91da0d273f.png)

**Comment by tandraschko** [comment]
OK, can you dig deeper?

**Comment by melloware** [comment]
OK i figured out why.  I am not quit sure but here is what is stored in VisibleColumnsMap:
```
form:idTreeTable:j_idt8
```
Which is the ID of the column header and correct which is why it hides the header.

But then when looping over the body here is the value of `column.getColumnKey`.
```
form:idTreeTable:0:j_idt8
```

it includes the row ID `0` so its not finding a match in the map.    It works fine now for `p:columns` the `columnKey` is correct and hides the body and header.

**Comment by tandraschko** [comment]
Could you check if it worked before in DataTable? Should be the same code and i didnt change the JS code. And the Bug already occurs on the JS side

**Comment by melloware** [comment]
I can confirm this same behavior was broken in 8.0 before any of these changes.  The toggler sends the column header ID which is correct but when looping over cells or nodes the columnKey contains the RowIndex in it as well and thus the MAP will never `containsKey`. I think I have a fix for you to review but I am sure you won't like it 😄

**Comment by melloware** [comment]
OK PR submitted I verified it fixes it for both Datatable and TreeTable and works for regular columns and `p:columns` as well.

**Comment by tandraschko** [comment]
i see, i think i can make a better fix tomorrow, let see :)

Thanks for super help!

**Comment by melloware** [comment]
No problem I thought you would have a better fix :)

**Comment by tandraschko** [comment]
the bug is quite stupid...
The Renderer loops the rows and apply the rowIndex on the DataTable, therefore all Columns#getClientId (which is used by #getColumnKey) get the rowIndex inside it.
The solution would be to eager create the columnKey and cache it. Or lazily remove the rowIndex

**Comment by tandraschko** [comment]
At least this would be easy for p:column, p:columns is even worse as its dyanmic, based on the columnIndex

**Comment by tandraschko** [comment]
commited, would be great if you could test a bit some cases and check the integration tests.

**Comment by melloware** [comment]
Retested a bunch of scenarios and also ran the integration tests and everything is working fine.

**Comment by tandraschko** [comment]
@melloware i think there is still some JS wrong.
If you deselect all but 1 row in the DT, the rowstyle is still only 50% applied, could you check it?

**Comment by melloware** [comment]
Deselect Rows or columns?

**Comment by tandraschko** [comment]
column sorry :D

**Comment by melloware** [comment]
ok let me look

**Comment by melloware** [comment]
OK I am running the 5117 reproducer and when I deselect all columns but Price I don't see any issues.  What am I missing?

**Comment by tandraschko** [comment]
![columns](https://user-images.githubusercontent.com/2485545/102221902-05c18900-3ee3-11eb-959f-6e7ed5f01385.png)

in firefox

**Comment by melloware** [comment]
Weird you are right its definitely a firefox issue doesn't happen on Chrome or Edge.  Let me see what I can find out.
