### ISSUE TITLE
WildFly 7.1-SNAPSHOT not deployable: CalendarRenderer 

### ISSUE THREAD

**Issue by mdzaebel** [primefaces/primefaces#5308]
## 1) Environment
- PrimeFaces version: PF 7.1-SNAPSHOT (checked out some days ago)
- Application server + version: WildFly 11
- Affected browsers: All

## 2) Expected behavior
Deployment with minimal XHTML should work

## 3) Actual behavior
SEVERE Critical error during deployment: : com.sun.faces.config.ConfigurationException: 
  Source Document: vfs:/C:/neu/servers/wildfly-11.0.0.Final/standalone/deployments/pf7-0.0.1-SNAPSHOT.war/WEB-INF/lib/primefaces-7.1-SNAPSHOT.jar/META-INF/faces-config.xml
  Cause: Unable to create a new instance of 'org.primefaces.component.calendar.CalendarRenderer': javax.faces.FacesException: com.sun.faces.spi.InjectionProviderException: java.lang.reflect.MalformedParameterizedTypeException
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:378)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:288)
	at com.sun.jsf-impl//com.sun.faces.config.processor.RenderKitConfigProcessor.addRenderers(RenderKitConfigProcessor.java:313)
	at com.sun.jsf-impl//com.sun.faces.config.processor.RenderKitConfigProcessor.process(RenderKitConfigProcessor.java:179)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.ManagedBeanConfigProcessor.process(ManagedBeanConfigProcessor.java:270)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.ValidatorConfigProcessor.process(ValidatorConfigProcessor.java:120)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.ConverterConfigProcessor.process(ConverterConfigProcessor.java:126)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.ComponentConfigProcessor.process(ComponentConfigProcessor.java:117)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.ApplicationConfigProcessor.process(ApplicationConfigProcessor.java:362)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:137)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:239)
	at com.sun.jsf-impl//com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:439)
	at com.sun.jsf-impl//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:227)
	at io.undertow.servlet//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:205)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
	at io.undertow.servlet//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads//org.jboss.threads.JBossThread.run(JBossThread.java:320)

**Comment by tandraschko** [comment]
I cant see anything what could be wrong.
Also it works fine for me in Mojarra and MyFaces.

Please try to dig into it, i dont have time to check it on wildfly.

**Comment by melloware** [comment]
I got the same error on WildFly 13 I will investigate.

**Comment by melloware** [comment]
OK did some debugging.  If I remove from faces-config-xml..
```xml
        <renderer>
            <component-family>org.primefaces.component</component-family>
            <renderer-type>org.primefaces.component.CalendarRenderer</renderer-type>
            <renderer-class>org.primefaces.component.calendar.CalendarRenderer</renderer-class>
        </renderer>
```

It then blows up with the same  error on DatePicker. If I then remove DatePicker...
```xml
        <renderer>
            <component-family>org.primefaces.component</component-family>
            <renderer-type>org.primefaces.component.DatePickerRenderer</renderer-type>
            <renderer-class>org.primefaces.component.datepicker.DatePickerRenderer</renderer-class>
        </renderer>
```

Everything starts up fine.  So it is something related to the refactoring of DatePicker/Calendar to use the same BaseCalendarRenderer.

**Comment by mdzaebel** [comment]
@melloware Thanks a lot for removing the wildcard generic types. However, pulling from the master, doesn't change, as it's in 7.1 milestone. Shouln't this be commited to the master too?

@tandraschko : According to [java-ee-survey-2018](https://arjan-tijms.omnifaces.org/2018/05/java-ee-survey-2018-results.html) WildFly (~60%) is by far the most used application server. What about adding it to the build server?

**Comment by melloware** [comment]
hmm are you sure?  I pulled from master and built and my Wildfly is working again.

**Comment by melloware** [comment]
it was fixed with this commit: https://github.com/primefaces/primefaces/commit/25991f9d5f81df5993122cacb7ce0c706e26cb5f#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by mdzaebel** [comment]
Ok, I validated, that your sources are correctly commited, but - in contrary to your experience - I now get the following error on WildFly 11:

INFO  WFLYWELD0003: Processing weld deployment pf7-0.0.1-SNAPSHOT.warINFO  Mojarra 2.2.13.SP4  für Kontext '/pf7' wird initialisiert.SEVERE Critical error during deployment: : com.sun.faces.config.ConfigurationException: 
  Source Document: vfs:/C:/neu/servers/wildfly-11.0.0.Final/standalone/deployments/pf7-0.0.1-SNAPSHOT.war/WEB-INF/lib/primefaces-7.1-SNAPSHOT.jar/META-INF/faces-config.xml
  Cause: Class 'org.primefaces.application.resource.DynamicResourcesPhaseListener' is missing a runtime dependency: java.lang.NoClassDefFoundError: Lorg/primefaces/util/Lazy;
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:364)
	at com.sun.jsf-impl//com.sun.faces.config.processor.LifecycleConfigProcessor.addPhaseListeners(LifecycleConfigProcessor.java:154)
	at com.sun.jsf-impl//com.sun.faces.config.processor.LifecycleConfigProcessor.process(LifecycleConfigProcessor.java:132)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.invokeNext(AbstractConfigProcessor.java:152)
	at com.sun.jsf-impl//com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:239)
	at com.sun.jsf-impl//com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:439)
	at com.sun.jsf-impl//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:227)
	at io.undertow.servlet//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:205)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:174)
	at io.undertow.servlet//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:239)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:99)
	at org.wildfly.extension.undertow//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads//org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.NoClassDefFoundError: Lorg/primefaces/util/Lazy;
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3062)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2249)
	at com.sun.jsf-impl//com.sun.faces.util.Util.classHasAnnotations(Util.java:1035)
	at com.sun.jsf-impl//com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.onPut(ApplicationInstanceFactoryMetadataMap.java:75)
	at com.sun.jsf-impl//com.sun.faces.application.ApplicationInstanceFactoryMetadataMap.scanForAnnotations(ApplicationInstanceFactoryMetadataMap.java:64)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.loadClass(AbstractConfigProcessor.java:424)
	at com.sun.jsf-impl//com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:301)
	... 25 more
Caused by: java.lang.ClassNotFoundException: org.primefaces.util.Lazy from [Module "deployment.pf7-0.0.1-SNAPSHOT.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 33 more

**Comment by melloware** [comment]
That is a different error you are getting "java.lang.NoClassDefFoundError: Lorg/primefaces/util/Lazy;"  Are you sure you don't have your maven builds messed up or two PF JAR's in your war?

**Comment by tandraschko** [comment]
yep, seems like a corrupted classpath.

we don't have any "build-server" - we just build primefaces and test with jetty and different JSF impls/versions, thats it.

**Comment by mdzaebel** [comment]
I cleaned the WildFly full 11 deployment directories and rebuild everything. I have an absolute minimal PF project with only a minimal index.xhtml and still the same exception occurs. If your primefaces-test (Jetty-based) would conform to JEE, it might be possible to reproduce the problem. It should be possible, to make the web.xml conforming (read some articles about it).

This is my minimal pom.xml (using only mvn commands):
``` xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.mdz</groupId>
	<artifactId>pf7</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<description>Primfaces 7 test project</description>
	<dependencies>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>7.0</version>
			<scope>provided</scope>
		</dependency> 
		<dependency>
			<groupId>org.primefaces</groupId>
			<artifactId>primefaces</artifactId>
			<version>7.1-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<build>
		<sourceDirectory>src</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.1</version>
				<configuration>
					<warSourceDirectory>WebContent</warSourceDirectory>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```
I'll try to checkout WildFly 13, as @melloware had no problems with it. Thanks for comments.

**Comment by tandraschko** [comment]
I'm sure there is something wrong at your side.
"runtime dependency: java.lang.NoClassDefFoundError: Lorg/primefaces/util/Lazy;"
just check our code, it's there.
Or check the generated JAR in the PF target dir - and your primefaces.jar

**Comment by mdzaebel** [comment]
yes, the war includes primefaces-7.1-SNAPSHOT.jar which includes the Lazy.class and it is in the deployment directory. Funny stuff - must be a local problem.

**Comment by melloware** [comment]
also do me a favor in your /standalone folder delete the folders /data /log and /tmp.  I have seen Jboss get cluttered with "junk" and deleting those folders usually fixes it.

**Comment by mdzaebel** [comment]
I stopped the server, deleted data,log,tmp (and additionally all file from deployments) rebuild, restarted and redeployed with a now changed exception:

 ```
Source Document: vfs:/C:/neu/servers/wildfly-11.0.0.Final/standalone/deployments/pf7-0.0.1-SNAPSHOT.war/WEB-INF/lib/primefaces-7.1-SNAPSHOT.jar/META-INF/faces-config.xml
  Cause: Class 'org.primefaces.component.imagecropper.ImageCropperRenderer' is missing a runtime dependency: java.lang.NoClassDefFoundError: org/apache/commons/io/input/BoundedInputStream
```
In fact, the class exists. So, I really have to reinstall my server, to verify the problem.

**Comment by tandraschko** [comment]
Its actual shaded to org.primefaces, no Idea whats wrong on your side

**Comment by mdzaebel** [comment]
Same problem on newly created WildFly 15, but PF has commons-io-2.4.jar.

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/input/BoundedInputStream
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.faces.util.Util.loadClass(Util.java:333)
	at com.sun.faces.config.processor.AbstractConfigProcessor.loadClass(AbstractConfigProcessor.java:423)
	at com.sun.faces.config.processor.AbstractConfigProcessor.createInstance(AbstractConfigProcessor.java:304)

**Comment by mdzaebel** [comment]
@melloware Could you attach a copy of your sample project, that worked?

**Comment by melloware** [comment]
Yes tomorrow when I am in the office.

**Comment by mdzaebel** [comment]
I succeeded with removing `<optional>true</optional>` for commons-io in PF pom.xml.

I still would recommend to add tests for most common application servers and to fix primefaces-test to be JEE conforming.

So thanks to @melloware and @tandraschko for your immediate help!!

**Comment by tandraschko** [comment]
As i said, there is something wrong at your side.
When i generate the primefaces.jar and check the bytecode, ImageCropperRenderer uses:
org/primefaces/shaded/commons/io/input/BoundedInputStream

**Comment by melloware** [comment]
agreed with @tandraschko you should not need to do this.  My WAR for Wildly just has PF 7.1 in the WEB-INF/lib and it works and starts fine.

**Comment by mdzaebel** [comment]
Thanks, unfortunately, reverting `<optional>true</optional>` lets the exception reappear. It's located in org/primefaces/shaded, as yours is. However, the runtime classpath seems to load it from a different point. `ImageCropperRenderer `imports `org.apache.commons.io.input.BoundedInputStream`. May be _maven-shade-plugin_ has problems for WildFly on Windows 8 but @melloware has no problems so I'm stuck with this.

**Comment by melloware** [comment]
I will post my war tomorrow. We have to get to the bottom of this.

**Comment by melloware** [comment]
@mdzaebel Download this WAR: http://melloware.biz/download/primefaces/melloware-wildfly.war

Load it in Wildfly and navigate to http://localhost:8080/melloware/jsf/ajax.html

Let me know how it goes.

**Comment by mdzaebel** [comment]
ok, will be late in the evening

**Comment by mdzaebel** [comment]
I successfully deployed your war on a newly installed WildFly 18. However, the URL has to be http://localhost:8080/melloware rather than http://localhost:8080/melloware/jsf/ajax.html (results in "Not Found").

Still, in my sample project, that depends on PF 7.1-SNAPSHOT, most optional settings in pom.xml of Primefaces lead to problems. E.g. if the optional JSON is required by implementation, classes of the respective relocated libs (org.json:json) are not found. Tested WildFly versions are 13,14,15,17,18.

**Comment by melloware** [comment]
OK so now you can extract my 7.1-SNAPSHOT from inside the WAR and replace yours inside your WAR?

it just makes no sense why you need those optional dependencies.

**Comment by mdzaebel** [comment]
Replacement did not work. However, looking through the target files of primefaces, I saw, that there are 3 different PF-Jars created. If I use primefaces-7.1-SNAPSHOT-shaded.jar in my WEB-INF/lib. it works. Otherwise, I get the above errors. So, how should I define my dependency in the pom in order to get the shaded jar?

**Comment by mdzaebel** [comment]
In order to depend on a shaded jar, you could create an own maven repository, install the shaded jar into it, and than depend on 7.1-SNAPSHOT-shaded, which is altogether not easy. Do you know easier solutions?

**Comment by melloware** [comment]
I am still struggling as to what the issue is as I can’t reproduce it. I just run “mvn clean install” on primefaces.  And you have proven my war works fine. So what are you doing differently?  I have no idea what you are talking about a shaded jar?

Can you post your War so I can try it?

**Comment by mdzaebel** [comment]
Sorry for the delay. Attached my war, that produces the ..BoundedInputStream ClassNotFoundException.

[pf7-0.0.1-SNAPSHOT.war.zip](https://github.com/primefaces/primefaces/files/3843756/pf7-0.0.1-SNAPSHOT.war.zip)

**Comment by melloware** [comment]
I don't see the attachment?

**Comment by mdzaebel** [comment]
Had to zip it

**Comment by melloware** [comment]
OK I see it now, trying it out

**Comment by melloware** [comment]
OK I see your problem.  

1. In your WEB-INF/lib your primefaces.jar is actually an exploded JAR of compiled classes. That explains the problem I get the same BoundedInputStream problem.

2. I deleted your /lib/primfaces.jar folder and replaced it will a real JAR primefaces-8.0-SNAPSHOT.jar and your war starts up fine.

So the issue is you have some strange configuration where your primefaces is being deployed exploded so the SHADED classes are not being generated properly which explains why you are getting the BoundedInputStream issue.  So if you are using Eclipse it seems like you projects are Linked.  I don't think you can run like that I think you need to run PrimeFaces as a JAR and not as a Linked project.

**Comment by mdzaebel** [comment]
Yes, the usual dependency in pom does not work. After "mvn clean install" on PF I have the following jars in the target directory:
- original-primefaces-7.1-SNAPSHOT.jar
- primefaces-7.1-SNAPSHOT-shaded.jar  (works)
- primefaces-7.1-SNAPSHOT.jar (does not work)

But how should I depend on the project in the pom (I use Eclipse) in order to get the shared jar? I could copy it into WEB-INF/lib but of course want to use a Maven dependency.

**Comment by melloware** [comment]
So if you are using Eclipse its linking your PrimeFaces source code.  You can either right click on the your WAR project and unlink the project.   Or close your Primefaces source code project in Eclipse and itwill go back to using your JAR version. 

I think your problem is that Eclipse is seeing your open PrimeFaces Source, and your WAR is using that project.  Try closing your Primefaces source code project and then rebuild or keep PrimeFaces open in a separate Eclipse and only have your WAR in Eclipse.  Its the Maven M2 Eclipse plugin that is doing this to you.

**Comment by mdzaebel** [comment]
Ok, thats a good explanation. I'll try it tomorrow. It's 0:04 in Germany. Thanks for your instant help!!

**Comment by mdzaebel** [comment]
After `mvn clean install` on Primefaces, closing it and redeploy my dependent project it works. So this is a solution, but should be mentioned as many could fall into this trap.

**Comment by melloware** [comment]
Nice!  yeah i think you are surprisingly in the minority of people who keep the PF source code open in the same Eclipse :)  But glad you got it resolved!

**Comment by mdzaebel** [comment]
Yes, thank you too, wonder where you get your energy to help so much in PF issues!
