### ISSUE TITLE
DataTable: rowsPerPage from paginator broken after using a filter

### ISSUE THREAD

**Issue by matinh** [primefaces/primefaces#5523]
## 1) Environment
- PrimeFaces version: 8.0-SNAPSHOT (commit 6b6c2be from 2020-01-15)
- Does it work on the newest released PrimeFaces version? Version? It works on 7.0, can't test 7.0.x.
- Does it work on the newest sources in GitHub? No, it's broken.
- Application server + version: Jetty 9.4.15 from primefaces-test
- Affected browsers: Tested with Firefox 67 and 71 but probably independent from browser

## 2) Expected behavior
DataTable has a paginator which supports a _{RowsPerPageDropdown}_ to select number of rows displayed per page. This dropdown should work even after filtering for a column was used.

## 3) Actual behavior
Once filtering was used, the rowsPerPage-dropdown stops working. The user has to change filter again, so apply to changes in the drowdown.

## 4) Steps to reproduce

* clone https://github.com/matinh/primefaces-test.git using the branch _dataTable-rowsPerPage_ with `git clone 'https://github.com/matinh/primefaces-test.git' -b dataTable-rowsPerPage`
* change directory `cd primefaces-test`
* run `mvn jetty:run-exploded`
* goto http://localhost:8080/primefaces-test/
* try changing the number of rows per page, which works
* now apply a filter (for example "o" in the second column) which triggers an AJAX request and reduces displayed rows correctly
* remove the filter and try again to change the number of rows per page, which now has no effect.
 
## Further comments
* This issue is a regression bug. It used to work with 7.0 but no longer works with recent 8.0-SNAPSHOT versions.
* This issues is probably related to issue #4931 respectively to the changes from PR #4956.

**Comment by melloware** [comment]
@matinh Our test team has been testing one of my apps on PF 8.0 and just discovered this issue as well.  Since you were involved in the original PR do you have a proposed fix for this issue?

**Comment by matinh** [comment]
I think I found the cause, which is actually the same as described in https://github.com/primefaces/primefaces/issues/4931#issuecomment-505859004: `UIData.setRows()` is called by [`FilterFeature` ](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java) from the `DataTable` component:
```java
    //update rows with rpp value
    String rppValue = params.get(clientId + "_rppDD");
    if (rppValue != null) {
        table.setRows(Integer.parseInt(rppValue));
    }
```

This is just, what has been fixed in #4931, but unfortunately only in one place. `UIData.setRows()` is called from 7 different locations (according to IntelliJ's call hierachy):
* `DataList.restoreMultiViewState()`  (org.primefaces.component.datalist)
* `DataView.restoreMultiViewState()`  (org.primefaces.component.dataview)
* `DataTableExporter.exportAll(FacesContext, DataTable, Object)`(2 usages)  (org.primefaces.component.datatable.export)
* `Carousel.setRows(int)`  (org.primefaces.component.carousel)
UIData.updatePaginationData(FacesContext, UIData)  (org.primefaces.component.api)
* `FilterFeature.encode(FacesContext, DataTableRenderer, DataTable)`  (org.primefaces.component.datatable.feature)
* `DataTable.restoreMultiViewState()`  (org.primefaces.component.datatable)

A fix for the `FilterFeatures` is quite trivial and would look like this:

```diff
--- src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java	(Revision 14241)
+++ src/main/java/org/primefaces/component/datatable/feature/FilterFeature.java	(Arbeitskopie)
@@ -121,7 +121,14 @@
         //update rows with rpp value
         String rppValue = params.get(clientId + "_rppDD");
         if (rppValue != null) {
-            table.setRows(Integer.parseInt(rppValue));
+            ValueExpression rowsVe = table.getValueExpression("rows");
+            ELContext elContext = context.getELContext();
+            if (isWriteable(elContext, rowsVe)) {
+                rowsVe.setValue(elContext, rppValue);
+            }
+            else {
+                table.setRows(Integer.parseInt(rppValue));
+            }
         }
 
         if (table.isLazy()) {
@@ -183,6 +190,10 @@
         }
     }
 
+    private boolean isWriteable(ELContext elContext, ValueExpression ve) {
+        return ve != null && !ve.isReadOnly(elContext);
+    }
+
     public void filter(FacesContext context, DataTable table, List<FilterMeta> filterMetadata, String globalFilterValue) {
         List filteredData = new ArrayList();
         Locale filterLocale = table.resolveDataLocale();
```

But we would probably have to apply it to all calls of setRows(). I'm not sure if this is a good solution. Anybody with more insights into PrimeFaces that can come up with a better solution?

**Comment by melloware** [comment]
Let me look at this more.

**Comment by melloware** [comment]
@matinh I am testing your fix and it still doesn't work.   Do these steps.

1. Set RowsPerPage to 1.
2. Filter String field by character "o".
3. use the Pagintor to go to Page 2.
4. Now set RowsPerPage back to 5...nothing happens.  That should cause the table to repaint with 5 rows.

**Comment by melloware** [comment]
Looking at before your original PR the only way I can seem to fix it is by always setting the "data" values like in this closed PR: https://github.com/primefaces/primefaces/pull/5524/files

**Comment by matinh** [comment]
As discussed in the PR #5524 always setting the data values re-introduces #4931 and is thus no valid solution.
So another idea for a fix would be: overwrite `setRows()` and `setFirst()` methods in `UIData` and check if there is a writable value-expression assigned. If it is, set the value of the VE, just like it is now done in `UIData.updatePaginationData()`. This way we don't need to change all calls to `setRows()`/`setFirst()` but have only one place to perform the necessary checks.

What do you think?

**Comment by melloware** [comment]
I say give it a try...

**Comment by matinh** [comment]
@melloware Ok, I now created PR #5526 which does as suggested above: the fix is in `setFirst()`/`setRow()` so all problematic places should be caught now.

In my tests the reproducers for this issue and for #4931 work now. Could you please review and also check your use-cases.

**Comment by melloware** [comment]
OK I just submitted a PR which fixes all the issues in #5523, #4931 and for #5493 and i regression tested them all.  @matinh can you give my PR a shot for all your use cases.

**Comment by MatthiasScherrerFGCZ** [comment]
Addendum: Even without any filtering, the issue persists.

1. Go to the showcase (https://www.primefaces.org/showcase/ui/data/datatable/paginator.xhtml) where the default rows per page is 10.
2. Go to page 5.
3. Select 15 from the rows per page drop down.
4. Nothing happens.

Is this also fixed by 0b3bab65696a6730b453ca8ac67c6cf91c0f9775?

**Comment by matinh** [comment]
You are right. And this is for sure related to the original problem.
But could you please open a separate issue for it and link it to this one. The original issues seems to be fixed.

**Comment by melloware** [comment]
@ProgrammingIsAwesome @matinh I just tested the showcase locally and its working fine.  The showcase has not been deployed since we made this fix so I can say yes your issue is fixed.

**Comment by MatthiasScherrerFGCZ** [comment]
@matinh @melloware So should I still make a separate issue and link to this one for completeness' sake?

**Comment by melloware** [comment]
No that is not necessary as it is covered by this issue.
