### ISSUE TITLE
SelectEvent returning null

### ISSUE THREAD

**Issue by MatheusRadeski** [primefaces/primefaces#5711]
Previously, I used java ee 7 and glassfish 4 and my code was working correctly. After switching to Jakarta ee 8 and payara the selectEvent used is returning null. 
In the selectEvent method the event is null. If I pass the selectObj () method directly in the ajax listener, it works.
Follow the code below.

[mavenproject1.zip](https://github.com/primefaces/primefaces/files/4359092/mavenproject1.zip)

Primefaces 6.2
Jakarta ee 8
Payara 5.201

**Comment by melloware** [comment]
Is that example runnable?   Would prefer you create an example that works with the Primefaces Test project: https://github.com/primefaces/primefaces-test

I don't think you are going to find any devs here to install Payara etc to try and test this out.

**Comment by MatheusRadeski** [comment]
> Esse exemplo pode ser executado? Prefere que você crie um exemplo que funcione com o projeto Primefaces Test: https://github.com/primefaces/primefaces-test
> 
> Acho que você não encontrará nenhum desenvolvedor aqui para instalar o Payara, etc., para tentar testar isso.

[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/4359715/primefaces-test-master.zip)

**Comment by MatheusRadeski** [comment]
[primefaces-test-master.zip](https://github.com/primefaces/primefaces/files/4359727/primefaces-test-master.zip)

**Comment by melloware** [comment]
`mvn clean jetty:run-exploded -Pmojarra22` - NullPointerException
`mvn clean jetty:run-exploded -Pmojarra23` - NullPointerException
`mvn clean jetty:run-exploded -Pmyfaces22` - No error but it doesn't look like its calling the handleSelect event
`mvn clean jetty:run-exploded -Pmyfaces23` - No error but it doesn't look like its calling the handleSelect event

**Comment by MatheusRadeski** [comment]
> 


I didn't understand. Here is calling the handleReturn but the event is null.

**Comment by melloware** [comment]
So the above was testing it with Mojarra 2.2, 2.3 which produce the NullPointerException.

With Myfaces 2.2 and 2.3 there is no NPE but the event is not being called because I don't see the `System.err.println` being called.

**Comment by MatheusRadeski** [comment]
> So the above was testing it with Mojarra 2.2, 2.3 which produce the NullPointerException.
> 
> With Myfaces 2.2 and 2.3 there is no NPE but the event is not being called because I don't see the `System.err.println` being called.


I didn't understand what I should do, I apologize, I'm starting with WEB development.

**Comment by melloware** [comment]
It looks like some kind of bug if you said this used to work before and now it doesn't work in 8.0.  So I marked it a "defect".

**Comment by dmatej** [comment]
Could it be related to this?
https://github.com/payara/Payara/pull/4592
https://github.com/payara/Payara/issues/4435

The bug is in PrimeFaces, but started to be visible after this change in buildParameters method, in Java EE8 respecting varargs: https://github.com/javaee/uel-ri/commit/849ec6859b65f4a500dfc71d5fe4fd60e8bad9c3?diff=split

Originally it was throwing IllegalArgumentException and then Primefaces catched the exception in AjaxBehaviorListenerImpl and **THEN** tried to call the correct method with one argument (the AjaxBehaviorEvent). After this change in Java EE 8 the ReflectionUtil.invokeMethod throws an ElException instead of IAE and this exception is not processed in PrimeFaces.

If PrimeFaces would try to call method with the event parameter first, it should fix this issue and it should not break Java EE7 implementations, but I don't understand reasons for those catch blocks:

![image](https://user-images.githubusercontent.com/302904/79903459-6a3f4d80-8413-11ea-85fe-8aeedd80c5ef.png)

**Comment by melloware** [comment]
Nice research. Let me investigate.

**Comment by tandraschko** [comment]
i will commit a possible fix, please retest and review

**Comment by tandraschko** [comment]
will close it for now, please come back if you have tested it

**Comment by melloware** [comment]
This does not fix it for Mojarra or MyFaces.   NPE is still being thrown and in MyFaces nothing happens and the SelectEvent is not called.

**Comment by tandraschko** [comment]
then i fixed a completly unrealted bug maybe :D
i will check the testproject now

**Comment by tandraschko** [comment]
I wonder what should happen here?

`newJSFManagedBean.handleReturn(org.primefaces.event.SelectEvent)`

i think thats just invalid EL here?

**Comment by tandraschko** [comment]
what happens in Mojarra:
we call the Ajax-Listener without arguments (but it actually has a argument) and the JSF/EL-Impl calls the method with null parameter
it should actually trhough a illegal-argument-exception

**Comment by tandraschko** [comment]
same happens in MyFaces, it just doesn't rethrow the exception AFAICS

**Comment by tandraschko** [comment]
ok to be honest, i'm not sure what the exact problem is

i also dont know if the syntax here is allowed:
`newJSFManagedBean.handleReturn(org.primefaces.event.SelectEvent)`
but if i remove the argument, the listener isn't found

nevertheless, i think PrimeFaces is doing correctly
- it has the correct SelectEvent when invoking AjaxBehaviorListenerImpl
- it always tries to invoke the non-arg-listener first
- per spec, if the parameters don't match, JSF/EL should throw a MethodNotFound/IllegalArgumentException which doesn't happen in this case

it just invokes the non-arg with NULL param
probably facelet doesn't extract the infos correctly?

this is out of scope of PrimeFaces

**Comment by tandraschko** [comment]
I general we could probably fix it by invoking the listener with the event first but the current codebase is tested since years even in old containers...

Im really not sure....

https://openliberty.io/docs/ref/javadocs/liberty-javaee8-javadoc/javax/el/ExpressionFactory.html#createMethodExpression-javax.el.ELContext-java.lang.String-java.lang.Class-java.lang.Class:A-

What should happen in EL if we call a MethodExpression created with params, invoked without params? And vice versa?
can you clarify @dmatej ?

**Comment by tandraschko** [comment]
FYI about the fallbacks in AjaxBehaviorListenerImpl.
We have 3 cases for p:ajax listener signature:

void listener()
void listener(AjaxBehaviorEvent)
void listener(CustomEventClass)

**Comment by dmatej** [comment]
> what happens in Mojarra:
> we call the Ajax-Listener without arguments (but it actually has a argument) and the JSF/EL-Impl calls the method with null parameter
> it should actually trhough a illegal-argument-exception

This is not true, you call directly the listener with an empty array, it throws the ELException and game over. 

If I understand specs well (and also jakarta.el/java.el sources):

> javax.el.MethodExpression
> invoke() must unwrap an InvocationTargetExceptions before re-throwing as an ELException.

And the sources - you can never receive IllegalArgumentException directly, it is always wrapped to ELException. Then method with argument is never called:

```
        } catch (IllegalAccessException iae) {
            throw new ELException(iae);
        } catch (IllegalArgumentException iae) {
            throw new ELException(iae);
        } catch (InvocationTargetException ite) {
            throw new ELException(ite.getCause());
        }
```

**Comment by dmatej** [comment]
Currently I am running TCK tests with our temporary fix (4 hours for a single run), I will tell you later. The temporary fix worked with PrimeFaces 5.2 and 8.0, because it throws IAE again like in old EL version, so PF catches it and calls the variant with argument correctly.

**Comment by tandraschko** [comment]
Im not sure. The code always worked for normal cases, not sure what is so special about this case.

We call the methodExpression, which has paramTypes.length=1 actually, with a empty array (size = 0).
Our codes assumes sinces ages - and it always worked - that the EL impl would through a MethodNotFound or IllegalArgumentException

**Comment by tandraschko** [comment]
I think our code is now fine regarding your change about wrapping the IAE with a ELException (see https://github.com/primefaces/primefaces/commit/e880d5ff6f143a1ffec2a5049e5979afb8fef960)
but the bug here is a different one as the ELException contains the NPE and not a IAE

**Comment by tandraschko** [comment]
Here is a plain reflection sample of our case:

```   
 public static class A {
        public void blub(String a) {
            System.err.println(a);
        }
    }
    
    public static void main(String[] args) throws Exception {
        Method m =  A.class.getMethod("blub", String.class);
        System.err.println(m);
        
        Object invoke = m.invoke(new A(), new Object[]{});
    }
```


Which clearly throws a IAE. Not sure why JSF/EL just invokes the method with a null value.

**Comment by tandraschko** [comment]
Yep, i dont think that the EL is correct here:
`newJSFManagedBean.handleReturn(org.primefaces.event.SelectEvent)`

I debugged Tomcat EL Impl and it seems that if AstValue#isParametersProvided returns true (which it does in this case), the params passed to MethodExpression#invoke are ignored.

it works fine for me if you change to:
`newJSFManagedBean.handleReturn`

and add the method signature:
`<cc:attribute name="dlgReturnListenner" method-signature="void listener(org.primefaces.event.SelectEvent)" />`

**Comment by tandraschko** [comment]
@dmatej i moved the tracking of your issue to: https://github.com/primefaces/primefaces/issues/5827

**Comment by dmatej** [comment]
Ok, I will have yet something to say, but I want to avoid confusing you like yesterday ;-)
Investigation continues ... we still have a workaround for PrimeFaces in EL, but it's an ugly hack.

**Comment by tandraschko** [comment]
Yep
IMO it better to remove the hack from EL as the EL impl is correct, PrimeFaces wasn't adjusted for EE8 in this corner

i think we will put the fix into 8.0.2, so users can upgrade if they have the same problem

**Comment by MatheusRadeski** [comment]
Was the problem fixed in version 8.0.2 of primefaces?
I did not find in the modification logs.

**Comment by tandraschko** [comment]
Nope as i dont think the bug is on our side. See the comments in this topic and https://github.com/primefaces/primefaces/issues/5827

**Comment by MatheusRadeski** [comment]
Today I add primefaces through dependency with Maven.
How could you solve this problem?
I don't know how to change the AjaxBehaviorListenerImpl.java class.

**Comment by tandraschko** [comment]
Dont know sorry. 
This was a workaround for a problem described here: https://github.com/primefaces/primefaces/issues/5711#issuecomment-617621170
for everything else IMO our code in PF is correct as the EL impl should throw a MethodNotFound
