### ISSUE TITLE
Datatable: Sorters/Filters indexed by Column#field

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6532]
**Describe the defect**
As of today, sorters and filters are contained in a map indexed by clientId. Using `LazyDataModel#load` method, actives sorters/filters are transformed into a map where field is the key. At least two reasons for that:
- UIColumn#columnKey useless at this point
- Easy for the users to retrieve a specific sorter/filter from this map

If you take that sample #6421 in lazy mode, this will cause a problem since several columns are configured on the same field, basically you'll end up with less sorters/filters than expected.

**1st Solution**
An easy & quick solution would be to only filter active elements of that map, but key remain `UIColumn#columnKey` and you lose retrieving sorter/filter by field name. At this point, instead of using maps, lists could be passed as parameters to `LazyDataModel#load` method

**2nd Solution**
Datatable no longer "authorized" having several columns with same field. Let's take a more concrete example #5162, the user wants to display three columns "year". It shows one significant enhancement to do, having a new filter constraint: range. But since it doesn't exist, he created two additionnal columns from/to, and to identify them with `UIColumn#field`

As a reminder, UIColumn#field is only relevant when sorting or/and filtering is enabled. Having field as key would ease the impl of methods such as `DataTable"updateSortByWithUserSortBy`. It would also prevent bug when multiviewstate is enabled, and JSF tree is no longer the same when user comes back on that page _(clientId will most likely change, and restoring table state would probably restore a wrong state for a column)_

Let me know what you think 😉

**Comment by melloware** [comment]
@jxmai interested in your thoughts here since its your use case.

**Comment by tandraschko** [comment]
third solution (bit ugly):
introduce a "key" attribute on the column, which defaults to "field". So @jxmai for usecase, you could add a second column with the same field, just with a "key" attribute

**Comment by Rapster** [comment]
Ideally, if we could get rid of columnKey from UIColumn, that would be great. Whether you're adding a new attribute, or reuse `UIColumn#field` it's the same. In #6421, I would do something like this:
```xml
<c:forEach begin="0" end="2" var="idx">
     <p:column field="#{dtBasicView.fields[idx]}" headerText="Color" filterBy="#{car.color}">
          <h:outputText value="#{car.color}" />
     </p:column>
</c:forEach>
``` 

_(Not sure using c:foreach is the best option though but i'm sure you get the idea 😅 )_

**Comment by tandraschko** [comment]
but that doesnt fix if we have 2 columns mapped on the same field?

**Comment by Rapster** [comment]
The idea is to have one column for one field, you may display the same value but the field have to be different. For #5162, it could be year, yearFrom, and yearTo

**Comment by jxmai** [comment]
Thanks for the invite:) For starter, I tested Rapster's pull request branch: https://github.com/primefaces/primefaces/pull/6486 up to commit: 4308246a2efe77aabbdefe7f23fbe702d2870be5 against the sample provided under https://github.com/primefaces/primefaces/issues/6421 (https://github.com/primefaces/primefaces/files/5398261/primefaces-test.zip), the filter is working as expected.

> The idea is to have one column for one field, you may display the same value but the field have to be different. For #5162, it could be year, yearFrom, and yearTo

One key note here is that we should prevent regression for users as the actual usage can be similar to what's below

For example, previously we can use the approach below to create datatable. Notice that the `filterBy` is resolved via index. 

```xml
<c:forEach begin="0" end="NUM_COLUMNS" varStatus="varStatus">
     <c:choose>
            <c:when test="{isDate}">
	        			<p:column headerText="#{cc.attrs.colHeaders[varStatus.index]}"
								filterBy="dataTableVar[cc.attrs.colProperties[varStatus.index]]"
								filterMatchMode="contains"
								style="#{cc.attrs.colStyles[varStatus.index]};">
								...
						</p:column>
			</when>

			<c:when test="{isNumber}">
	        			<p:column headerText="#{cc.attrs.colHeaders[varStatus.index]}"
								filterBy="dataTableVar[cc.attrs.colProperties[varStatus.index]]"
								filterMatchMode="contains"
								style="#{cc.attrs.colStyles[varStatus.index]};">
								...
						</p:column>
			</when>
			...
     </c:choose>
</c:forEach>
```

**Comment by Rapster** [comment]
Does this sample actually work? I'm pretty sure it won't in lazy mode

**Comment by jxmai** [comment]
The filter does not work when we add `lazy=true`. If I am not mistaken, it hasn't been working in lazy mode in the first place (since previous versions) :thinking: .Just curious how much impact will be, I would prefer the sample to work as is in non-lazy mode if possible:) . The first solution seems like having less impact

**Comment by Rapster** [comment]
Yeah doesn't work for the same reason as #6421

**Comment by tandraschko** [comment]
This one is related, i fixed columnKey generation: https://github.com/primefaces/primefaces/issues/5117

**Comment by tandraschko** [comment]
Im still not sure here. Maybe we should leave it as it is and pass columnKey as map-key also to LazyDataModel

**Comment by Rapster** [comment]
Yeah I was thinking about that, if you put everything in the new `ColumnMeta`/`ColumnDescription`/`ColumnDefinition` class, field can't be the key since you might have no sorters/filters enabled. Restoring MVS through columnKey/clientId is still a problem, but this is another issue. Also, I think you meant pass field as key to LazyDataModel

**Comment by tandraschko** [comment]
why is MVS still a problem? because auto-generated j_id might change? Users can simply set p:column id="..." then.

> Also, I think you meant pass field as key to LazyDataModel

Nope, thats what we currently do! If we merge all to ColumnMeta and pass this to LazyDataModel, i would better to use `Map<ColumnKey, ColumnMeta>` or just a `List<ColumnMeta>` as `Map<Field, ColumnMeta>` would only work if we pass only sort/filter-active ColumnMeta.

**Comment by Rapster** [comment]
> why is MVS still a problem? because auto-generated j_id might change? Users can simply set p:column id="..." then.

You're only postponing the issue doing so, table component could change position in the JSF tree and then you'll have the same problem. Even if you're setting an id to the table, same thing can happen. It's not an easy problem to solve as long as columnKey is based on a "volatile" value

> `Map<ColumnKey, ColumnMeta>` or just a List<ColumnMeta> as Map<Field, ColumnMeta> would only work if we pass only sort/filter-active ColumnMeta.

-  `Map<ColumnKey, ColumnMeta>`: columnKey (which is a clientId) is not really helpful for users
- `List<ColumnMeta>`: yep sounds good

> Map<Field, ColumnMeta> would only work if we pass only sort/filter-active ColumnMeta.

I don't see what else you need at this point

**Comment by tandraschko** [comment]
> You're only postponing the issue doing so, table component could change position in the JSF tree

Sure but thats another topic. Then we would need on each MultiViewStateAware-component a attr called "mvsKey" instead of the clientId.

> It's not an easy problem to solve as long as columnKey is based on a "volatile" value

users can simple set id="brand" e.g., its the same as you would index by #field but more flexible.
