### ISSUE TITLE
DataTable: clean up selection

### ISSUE THREAD

**Issue by Rapster** [primefaces/primefaces#6575]

**Comment by melloware** [comment]
@Rapster I never thought about it but is this issue you are fixing similar to this one:
https://github.com/primefaces/primefaces/issues/3551

Because in that ticket they talk about lost selections while updating with a p:poll and they discussed storing the client side state in `localStorage` etc.  Is your PR solving the same issue as in that ticket or is that ticket different?

**Comment by Rapster** [comment]
I don't know what I took that day, but this sample I have given seems to work... 😅 I'll probably recycle/or create a new ticket because the PR fix several things and clean up selection code. I'll have a look on #3551 @melloware as soon as I can

**Comment by Rapster** [comment]
@melloware #3351 is something different

**Comment by melloware** [comment]
OK wasn't sure. I think i can solve #3351 pretty easily with localStorage no?

**Comment by Rapster** [comment]
I didn't give too much thoughts to be honest, But yeah most probably, it sounds very similar to those issue with JSF components scope, states need to be restored after a request (we use StateHelper to fix this), maybe for js widgets LocalStorage could be the solution on client side

**Comment by tandraschko** [comment]
I checked the related issue and the basic case (select multiple rows and update it) should be fixed by this PR actually.
After that i would close it. localStorage etc. is out of scope by far.

**Comment by Rapster** [comment]
Which related issue?

**Comment by tandraschko** [comment]
#3551

**Comment by Rapster** [comment]
All I can say is that this PR doesn't fix the following scenario:
- select row
- update
- select another row pressing shift 
- expecting range to be selected

That's what I understand from #3551

**Comment by tandraschko** [comment]
hmm, does it work without the "update" step? It should work theoretically, but we can check it afterwards of course.

**Comment by Rapster** [comment]
Yes it will work, basically client state is lost after update, and since selecting a range is based on a state, it won't work. I wonder if we could make it work without originRowIndex... can be discussed later

**Comment by melloware** [comment]
Yep I think #3551 I could fix pretty easily with localStorage and only reloading it upon component update.

**Comment by fanste** [comment]
There seems to be a chicken-egg problem when lazy mode is combined with multi-view-state.

`DataTableRenderer#preRender` invokes `DataTable#restoreMultiViewState` which decodes the selection using the changes from this issue. The decode-routine tries to resolve the real object behind the row-key using the data model. But that data model is not yet populated as `DataTable#loadLazyData` is invoked after `DataTable#restoreMultiViewState`.

It is also not possible to simply switch both code blocks, as `DataTable#restoreMultiViewState` restores filter and sort that is required by `DataTable#loadLazyData`.

I think the best solution would be to split up `DataTable#restoreMultiViewState` into two methods. The first one restores everything that is required for data loading and the second method does everything, that requires that loaded data. That should not be any overhead regarding performance and it should be usable for lazy and non-lazy data tables.

**Comment by melloware** [comment]
@fanste can you provide a PR of what you were thinking?

**Comment by fanste** [comment]
We just tested our solution and it works. But implement it nicely a change to the interface `MultiViewStateAware` is needed.

`restoreMultiViewState()` would get `restoreMultiViewState(boolean runDataIndepententRestore, boolean runDataDependentRestore)` or something like that.

In case of lazy mode the usage would look like 
```
if (table.isLazy()) {
    if(table.isMultiViewState()) {
        table.restoreMultiViewState(true, false);
    }

    // all the lazy stuff

    if(table.isMultiViewState()) {
        table.restoreMultiViewState(false, true);
    }
}
```

in case of non-lazy mode it would look like 
```
else {
    if (table.isMultiViewState()) {
        table.restoreMultiViewState(true, true);
    }

    // all the non-lazy stuff
}
```

If such a change is tolerated, I will provide the PR.

**Comment by Rapster** [comment]
Better to provide a PR to assess all the changes 😉

**Comment by Rapster** [comment]
Can you create a ticket for this issue, explaining the non technical problem. ideally with a reproducer plz
