### ISSUE TITLE
TreeTable: after filtering and changing value during ajax old filtered data is still shown

### ISSUE THREAD

**Issue by christophs78** [primefaces/primefaces#8073]
Same issue like https://github.com/primefaces/primefaces/issues/7845 for DataTable.
Worked with PF8, does not work with PF10.
I´ll provide a Integrationtest. (IT will show us whether the issue is still there with PF11. My personal feeling says we did not fix this yet for TreeTable.)

**Comment by tandraschko** [comment]
i think we should fix it for 11.0
would be great if you can provide a PR

**Comment by christophs78** [comment]
yep, should be fixed for 11.0.0

**Comment by melloware** [comment]
@christophs78 @tandraschko it looks like this ticket is complete but its still open?

**Comment by christophs78** [comment]
https://github.com/primefaces/primefaces/pull/8078#issuecomment-971826271

**Comment by christophs78** [comment]
We added kind of a manual work-around but did not fix the root cause.

**Comment by melloware** [comment]
Thanks I was having trouble figuring out where this stood!

**Comment by tandraschko** [comment]
closing in favor of #12795
