### ISSUE TITLE
PF10 DataTable: rows attribute get overriden with default value 

### ISSUE THREAD

**Issue by james-cslucas** [primefaces/primefaces#9726]
Hi, 

I am using primefaces-10.0.0.jar. I got similar issue #6132 DataTable: rows attribute get overriden with default value. 

when the rows attribute is from a properties file, the pagination is not working. but if I hardcode it to a number, it is working as expected. 

not working xhtml:
```xml
<p:datatable row="#{default_row_count}">
</p:datatable>
```

working xhtml:
```xml
<p:datatable row="10">
</p:datatable>
```

Any work-around for this?

Thanks,
James

**Comment by melloware** [comment]
This has been fixed already please upgrade to PF 11 or 12.

**Comment by melloware** [comment]
Looks like it was fixed in 10.0.0

**Comment by james-cslucas** [comment]
Hi Melloware,

the expression is from a properties file, but yes it is a number. 

Thanks,
James

**Comment by melloware** [comment]
@OBreidenbach you originally reported this issue for 10 and I thought it was fixed?

If someone provides an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project we can look at it.

**Comment by OBreidenbach** [comment]
It was fixed in release 10 already.

**Comment by ivancsl** [comment]
Hi, just want to clarify that this is the html code:
<p:dataTable rows="#{msg.TABLE_ROWS_DEFAULT}"

the message properties file has this:
TABLE_ROWS_DEFAULT=50

We are using pf 10 but the issue is still happening. The html cannot convert the value to integer 50.

**Comment by melloware** [comment]
Please follow the issue template or provide an executable example using the [PrimeFaces Test](https://github.com/primefaces/primefaces-test) project.  It is the only way developers can debug your problem to help.

**Comment by jepsar** [comment]
@ivancsl The rows attribute must be an `Integer`, not a `String`. That might be your issue.

**Comment by ivancsl** [comment]
@jepsar , how do I force the value that I retrieve to integer? thanks!

**Comment by jepsar** [comment]
That's basic Java stuff. Can you first please confirm that this was the issue?

**Comment by ivancsl** [comment]
yes that's the issue. incompatible types
